In [1]:
import polars as pl

import os
import logging
import polars as pl

from metrics.metrics import MetricsCalculator
from preprocess_data.datae2e import DataE2E

logging.basicConfig(level=logging.INFO, format="[%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

def run_metrics(calculate_mfbvar: bool = True, calculate_dfm: bool = True, folder: str = "preds") -> None:
    logger.info("Start calculating metrics")

    if calculate_mfbvar:
        logger.info("MFBVAR metrics calculation will be performed too")
    if calculate_dfm:
        logger.info("DFM metrics calculation will be performed too")

    train, valid, train_valid, test, avail_features_full = DataE2E().run()

    gb_pred_pl = pl.read_csv(f"{folder}/gb_pred_test.csv").with_columns(
        pl.col("date").cast(pl.Date)
    )

    ngb_pred_pl = pl.read_csv(f"{folder}/ngb_pred_test.csv").with_columns(
        pl.col("date").cast(pl.Date)
    )

    tabnet_pred_pl = pl.read_csv(f"{folder}/tabnet_pred_test.csv").with_columns(
        pl.col("date").cast(pl.Date)
    )

    preds_list = [gb_pred_pl, ngb_pred_pl, tabnet_pred_pl]
    ml_model_names = ["gb", "ngb", "tabnet"]
    target_names = ["gdp_log_d4", "cons_log_d4", "inv_log_d4", "inv_cap_log_d4"]

    metrics = MetricsCalculator(
        preds_list, ml_model_names, target_names, pl.concat([train, valid, test]), folder
    ).get_metrics(calculate_mfbvar, calculate_dfm)

    os.makedirs(f"{folder}", exist_ok=True)
    metrics.write_csv(f"{folder}/metrics.csv")

    logger.info("All metrics was calculated")

In [2]:
import config
### Выюерите папку в которую рассчитаются метрики и длину тестовой выборки (12 или 24)
config.TEST_LEN=24
folder = "preds_len24"

run_metrics(calculate_mfbvar=True, calculate_dfm=True, folder= folder)

[INFO] Start calculating metrics
[INFO] MFBVAR metrics calculation will be performed too
[INFO] DFM metrics calculation will be performed too
[INFO] All metrics was calculated

In [3]:
import polars as pl
metrics = pl.read_csv(f"{folder}/metrics.csv")
metrics

shape: (576, 8)
┌─────────┬──────────────┬─────────────┬──────────┬─────────────┬───────┬────────────┬─────────────┐
│ horizon ┆ avaliability ┆ features_ty ┆ rmse     ┆ target_name ┆ model ┆ rmse_naive ┆ rel_rmse_na │
│ ---     ┆ ---          ┆ pe          ┆ ---      ┆ ---         ┆ ---   ┆ ---        ┆ ive         │
│ i64     ┆ i64          ┆ ---         ┆ f64      ┆ str         ┆ str   ┆ f64        ┆ ---         │
│         ┆              ┆ str         ┆          ┆             ┆       ┆            ┆ f64         │
╞═════════╪══════════════╪═════════════╪══════════╪═════════════╪═══════╪════════════╪═════════════╡
│ 1       ┆ 1            ┆ d12         ┆ 0.030999 ┆ gdp_log_d4  ┆ gb    ┆ 0.038446   ┆ 0.806302    │
│ 1       ┆ 1            ┆ rolling     ┆ 0.036563 ┆ gdp_log_d4  ┆ gb    ┆ 0.038446   ┆ 0.951044    │
│ 1       ┆ 2            ┆ d12         ┆ 0.027697 ┆ gdp_log_d4  ┆ gb    ┆ 0.038446   ┆ 0.720433    │
│ 1       ┆ 2            ┆ rolling     ┆ 0.032764 ┆ gdp_log_d4  ┆ gb    ┆ 0.038446   ┆ 0.85221     │
│ 1       ┆ 3            ┆ d12         ┆ 0.030027 ┆ gdp_log_d4  ┆ gb    ┆ 0.038446   ┆ 0.781029    │
│ …       ┆ …            ┆ …           ┆ …        ┆ …           ┆ …     ┆ …          ┆ …           │
│ 5       ┆ 3            ┆ d12         ┆ 0.169993 ┆ inv_cap_log ┆ dfm   ┆ 0.077073   ┆ 2.205602    │
│         ┆              ┆             ┆          ┆ _d4         ┆       ┆            ┆             │
│ 4       ┆ 2            ┆ d12         ┆ 0.136489 ┆ inv_cap_log ┆ dfm   ┆ 0.07974    ┆ 1.711681    │
│         ┆              ┆             ┆          ┆ _d4         ┆       ┆            ┆             │
│ 6       ┆ 2            ┆ d12         ┆ 0.109163 ┆ inv_cap_log ┆ dfm   ┆ 0.080909   ┆ 1.349211    │
│         ┆              ┆             ┆          ┆ _d4         ┆       ┆            ┆             │
│ 4       ┆ 1            ┆ d12         ┆ 0.122218 ┆ inv_cap_log ┆ dfm   ┆ 0.07974    ┆ 1.532717    │
│         ┆              ┆             ┆          ┆ _d4         ┆       ┆            ┆             │
│ 4       ┆ 3            ┆ d12         ┆ 0.165395 ┆ inv_cap_log ┆ dfm   ┆ 0.07974    ┆ 2.074191    │
│         ┆              ┆             ┆          ┆ _d4         ┆       ┆            ┆             │
└─────────┴──────────────┴─────────────┴──────────┴─────────────┴───────┴────────────┴─────────────┘

In [4]:
best_metrics = metrics.group_by(
    [
        'target_name',
        'horizon',
        'avaliability',
     ]
).agg(
    pl.col('rel_rmse_naive').min().alias('best_rel_rmse_naive'),
    pl.col('model').sort_by('rel_rmse_naive').first().alias('best_model'),
    pl.col('features_type').sort_by('rel_rmse_naive').first().alias('best_features_type'),
).sort(
    [
        'target_name',
        'horizon',
        'avaliability',
    ]
)
best_metrics.filter(
    pl.col("target_name") == "inv_cap_log_d4"
)

shape: (18, 6)
┌────────────────┬─────────┬──────────────┬─────────────────────┬────────────┬────────────────────┐
│ target_name    ┆ horizon ┆ avaliability ┆ best_rel_rmse_naive ┆ best_model ┆ best_features_type │
│ ---            ┆ ---     ┆ ---          ┆ ---                 ┆ ---        ┆ ---                │
│ str            ┆ i64     ┆ i64          ┆ f64                 ┆ str        ┆ str                │
╞════════════════╪═════════╪══════════════╪═════════════════════╪════════════╪════════════════════╡
│ inv_cap_log_d4 ┆ 1       ┆ 1            ┆ 1.015458            ┆ ngb        ┆ d12                │
│ inv_cap_log_d4 ┆ 1       ┆ 2            ┆ 0.808589            ┆ ngb        ┆ d12                │
│ inv_cap_log_d4 ┆ 1       ┆ 3            ┆ 1.062723            ┆ ngb        ┆ d12                │
│ inv_cap_log_d4 ┆ 2       ┆ 1            ┆ 0.872692            ┆ ngb        ┆ d12                │
│ inv_cap_log_d4 ┆ 2       ┆ 2            ┆ 0.956576            ┆ gb         ┆ d12                │
│ …              ┆ …       ┆ …            ┆ …                   ┆ …          ┆ …                  │
│ inv_cap_log_d4 ┆ 5       ┆ 2            ┆ 0.691301            ┆ ngb        ┆ d12                │
│ inv_cap_log_d4 ┆ 5       ┆ 3            ┆ 0.579152            ┆ tabnet     ┆ rolling            │
│ inv_cap_log_d4 ┆ 6       ┆ 1            ┆ 0.680327            ┆ ngb        ┆ rolling            │
│ inv_cap_log_d4 ┆ 6       ┆ 2            ┆ 0.684909            ┆ ngb        ┆ rolling            │
│ inv_cap_log_d4 ┆ 6       ┆ 3            ┆ 0.607964            ┆ ngb        ┆ d12                │
└────────────────┴─────────┴──────────────┴─────────────────────┴────────────┴────────────────────┘